baseurl = "/"
languageCode = "en-us"
title = "TLC DOCS"
theme = "docDock"
disqusShortname = ""
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10
canonifyurls = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  description = ""
  cover = "images/cover.jpg"
  author = ""
  authorlocation = ""
  authorwebsite = ""
  bio= "my bio"
  logo = "images/logo.png"
  googleAnalyticsUserID = ""
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = ""
  githubName = ""
  twitterName = ""
  # facebookName = ""
  # linkedinName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = true
  [params.social]
    twitter = ""
