#baseurl = "/"
languageCode = "en-us"
title = "TLC DOCS"
theme = "docdock"
#disqusShortname = ""
# Enable Google Analytics by inserting your tracking code
#googleAnalytics = ""
# Define how many posts should appear on a site
#paginate = 10
#canonifyurls = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
#editURL = "https://github.com/tlcMattLarson/casper-cms-template/content/"
noHomeIcon = false # default is false
noSearch = false # default is false
showVisitedLinks = true # default is false
# themeStyle = "theme" # overide base css
themeVariant = "gray" # choose theme variant "green", "gold" , "gray", "blue" (default)
ordersectionsby = "weight" # ordersectionsby = "title"
